name: flutter_utils
description: Package para facilitar desenvolvimento de apps flutter
version: 0.0.1
author: Saulo Andrioli
homepage:

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.2.0
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: