name: flutter_utils
description: Package para facilitar desenvolvimento de apps flutter
version: 0.0.2
author: Saulo Andrioli
homepage: none

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
