name: flutter_utils
description: Package para facilitar desenvolvimento de apps flutter
version: 0.0.2
author: Saulo Andrioli
homepage: none
publish_to: none

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
